channels:
  - defaults
dependencies:
  - asn1crypto=1.3.0=py36_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - chardet=3.0.4=py36_1003
  - idna=2.8=py36_0
  - pip=20.0.2=py36_1
  - pycparser=2.19=py36_0
  - pyopenssl=19.1.0=py36_0
  - pysocks=1.7.1=py36_0
  - requests=2.22.0=py36_1
  - setuptools=45.2.0=py36_0
  - six=1.14.0=py36_0
  - urllib3=1.25.8=py36_0
  - wheel=0.34.2=py36_0
  - pip:
    - git+https://github.com/matplotlib/basemap.git
    - cycler==0.10.0
    - kiwisolver==1.1.0
    - matplotlib==3.1.3
    - numpy==1.18.1
    - polyline==1.4.0
    - pyparsing==2.4.6
    - pyproj==2.5.0
    - pyshp==2.1.0
    - python-dateutil==2.8.1
    - python-dotenv==0.11.0
